### ISSUE TITLE
/app/bin/dad-run: line 27: /app/opt/wine/bin/wine: cannot execute: required file not found

### ISSUE THREAD

**Issue by abclution** [nmlynch94/com.darkanddarker.DaD#48]
Followed the instructions but stuck after the flatpak installs.

flatpak run com.darkanddarker.DaD

grep: /home/User/.var/app/com.darkanddarker.DaD/data/prefix/user.reg: No such file or directory
/app/bin/dad-run: line 27: /app/opt/wine/bin/wine: cannot execute: required file not found

**Comment by nmlynch94** [comment]
You may be missing 32-bit libraries on your system. What distro are you using?

**Comment by nmlynch94** [comment]
Proxmox as in this is on a VM? Are you doing GPU passthrough or something? 

I'll likely need to see the installation log if you want to reinstall:

`flatpak remove --delete-data com.darkanddarker.DaD`

**Comment by nmlynch94** [comment]
Feel free to reply if you have more information and I can reopen.
