### ISSUE TITLE
Error on game launch

### ISSUE THREAD

**Issue by hostsys** [nmlynch94/com.darkanddarker.DaD#55]
Hi there! This project is awesome, thank you.

I'm not sure whether this is within scope but currently I am getting an error after pressing play, as you can see in the attached image.
After pressing Okay, it will throw another of the same error dialogues and the button will change from Stop back to Play again.
Any help would be appreciated, thank you!

![2024-05-25_06-55](https://github.com/nmlynch94/com.darkanddarker.DaD/assets/68484424/ffb5b02c-1ae3-40f3-9e7f-4773a8473ec2)

**Comment by nmlynch94** [comment]
Hello! Is this still happening? It looks like the servers were under maintenance when you posted this ticket according to the discord.

**Comment by hostsys** [comment]
Yep, still happening. I've tried running it via Lutris in a container using their dated install script as well and get the same error which makes me think it might be a Wine error? It didn't throw anything in the terminal so I'm unsure of how to troubleshoot.

**Comment by nmlynch94** [comment]
Hmmm. I'm unfortunately not able to reproduce this on my machine. Reinstall works as expected. They unfortunately don't expose any application logs, and I'm pretty sure error code 9 is coming from Dark and Darker so hard to tell what may be going wrong.

**Comment by hostsys** [comment]
The new Steam release came at a good time! Thanks for your replies :]
